//=========================================================
// src/adc0_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

// global constants
#define ZERO 0
#define ONE 1
#define RESOLUTION 1024.0
#define VREF 3.3

// global variables
uint8_t ADC0DATA = 0;
float ADC0Voltage = 0;
// pin declaration
//#define ADC0 P1_B7

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

uint8_t measureADC0 (){
  ADC0CN0_ADINT = 0; // clear interrupt flag
  ADC0CN0_ADBUSY = 1; // start conversion
  while (!ADC0CN0_ADINT); // wait for end of conversion
  return ADC0; // converted value
}

float getADC0Data (float ADC0DATA) {
  return (ADC0DATA*(VREF/RESOLUTION));
}


//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$

      ADC0DATA = measureADC0();

      ADC0Voltage = getADC0Data(ADC0DATA);
  }                             
}
