//=========================================================
// src/adc2_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

// Global constants
#define ZERO 0
#define ONE 1
#define RESOLUTION 1024.0
#define VREF 3.3
#define LSB_CONSTANT (VREF/RESOLUTION)
#define PERCENTAGE 100

// Global variable
uint16_t adc0_data = 0;
float adc0_voltage = 0;
uint16_t adc_percentage = 0;

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

uint16_t measureADC0 (){
  ADC0CN0_ADINT = 0;
  ADC0CN0_ADBUSY = 1;
  while (!ADC0CN0_ADINT);
  return ADC0;
}

float getADC0Data (float adc0_data) {
  return (adc0_data * LSB_CONSTANT);
}

uint16_t getPercentage (uint16_t adc0_data) {
  return ((adc0_data / 1023) * PERCENTAGE);
}


//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$

      adc0_data = measureADC0();
      adc0_voltage = getADC0Data(adc0_data);
      adc_percentage = getPercentage(adc0_data);

  }                             
}
