//=========================================================
// src/ledButton3_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

// global constants
#define ZERO 0
#define ONE 1

// pin declaration
#define LED0 P1_B4
#define BTN0 P0_B2

// counters and other helper variables
extern volatile uint16_t counter;
uint8_t b_is_running = 1;


//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  while (counter < 50);
  LED0 = ZERO;
  counter = ZERO;

  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$

      if ((counter < 200) && (BTN0 == ZERO)) {
          LED0 = ONE;
      }

      /*
      //counter = 0;
      if (b_is_running == 1)
      {
          //counter = ZERO;
          while (counter < 50);
          LED0 = ZERO;
          //counter = 0;

          if ((BTN0 == ZERO))
          {
              //counter = 0;
              if (counter < 250)
              {
                  LED0 = ONE;
                  b_is_running = ZERO;

              }else
                {
                  counter = 0;
                }
         }
      }

      */
  }                             
}
