//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>

// global constants
#define ZERO 0

// pin declaration
#define LED0 P1_B4

// variables
volatile uint8_t counter = 0;
volatile uint8_t max_value = 100;

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn) //1000Hz
  {
    counter++;
    TMR2CN0_TF2H = 0;

    if (counter == max_value)
    {
        LED0 = !LED0;
        counter = ZERO;
    }

  }

