//=========================================================
// src/shift1_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

// global constants
#define ZERO 0
#define ONE 1
#define EIGHT 8

// shift register defines
#define SRCLR P2_B1
#define SER P1_B7
#define SRCLK P0_B1
#define RCLK P0_B2
#define OE P1_B6

//data to display
#define D_OUT 8U
#define C_OUT 4U
#define B_OUT 2U

uint8_t iterator;
uint16_t i;

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

void delay (uint8_t max_value) {
  for (i = 0; i < max_value; ++i) {
      while (!TCON_TF0);
      TCON_TF0 = ZERO;
  }
}


void display_led (uint8_t input_data) {
  OE = ONE;

  for (iterator = 0; iterator < EIGHT; ++iterator) {
      SER = (input_data >> (7-iterator)) & 1U;
      SRCLK = ONE;
      SRCLK = ZERO;
  }

  RCLK = ZERO;
  RCLK = ONE;

  OE = ZERO;
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$

      display_led(B_OUT);
      delay(2000);
      display_led(B_OUT);
      display_led(C_OUT);
      delay(1000);
      display_led(D_OUT);
      delay(2000);
      display_led(C_OUT);
      delay(1000);
  }                             
}
